<?php

namespace MH\PlatformBundle\Repository;
use MH\PlatformBundle\Entity\animal;

/**
 * animalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class animalRepository extends \Doctrine\ORM\EntityRepository
{
  public function getAnimalByUser($id){
    $qb=$this->createQueryBuilder('a')
        ->where('a.user = :id')
        ->orderBy('a.nom','ASC')
        ->setParameter('id',$id);
    return $qb;
  }

}
