<?php

namespace MH\PlatformBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
  public function commentFindAll($pubId){
    $qb=$this->createQueryBuilder('c')
        ->innerJoin('c.user','u','WITH','c.publication=:pubId')
        ->addSelect('u')
        ->setParameter('pubId',$pubId);

        return $qb->getQuery()->getResult();
  }
}
