<?php

namespace MH\PlatformBundle\Repository;

/**
 * publicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class publicationRepository extends \Doctrine\ORM\EntityRepository
{
  public function pubsFindAll(){
    $qb=$this->createQueryBuilder('p')
        ->leftJoin('p.user','u')
        ->leftJoin('p.images','i')
        ->leftJoin('p.animals','pa')
        ->addSelect('u')
        ->addSelect('i')
        ->addSelect('pa');
        return $qb->getQuery()->getResult();
  }
}
