mh_platform_homepage:
    path:     /
    defaults: { _controller: MHPlatformBundle:Default:index }

index:
    path:     /accueil
    defaults: { _controller: MHPlatformBundle:Pub:index }

consulter:
    path:     /consulter/{id}
    defaults: { _controller: MHPlatformBundle:Pub:consulter }

ajouter:
    path:     /ajouter
    defaults: { _controller: MHPlatformBundle:Pub:ajouter }

supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: MHPlatformBundle:Pub:supprimer }
